VERSION 0.6
FROM golang:1.19.3-alpine
WORKDIR /aoc

deps:
    COPY go.mod go.sum ./
    RUN go mod download
    # Output these back in case go mod download changes them.
    SAVE ARTIFACT go.mod AS LOCAL go.mod
    SAVE ARTIFACT go.sum AS LOCAL go.sum

build:
    FROM +deps
    COPY *.go .
    RUN go build -o dist/solution *.go
    SAVE ARTIFACT dist/solution AS LOCAL dist/solution

fmt:
    FROM +deps
    COPY *.go .
    RUN go fmt *.go
    SAVE ARTIFACT *.go AS LOCAL .

run:
    BUILD +run-one
    BUILD +run-two

run-one:
    FROM +build

    COPY data ./data
    COPY +build/solution .

    RUN --no-cache /aoc/solution ./data/input.txt one

run-two:
    FROM +build

    COPY data ./data
    COPY +build/solution .

    RUN --no-cache /aoc/solution ./data/input.txt two

bench:
    FROM +deps
    COPY *.go .
    COPY data ./data
    RUN --no-cache go test -bench=. -benchmem -benchtime=5s

clean:
  LOCALLY
  RUN rm -rf dist
  RUN rm -rf *.out
  RUN rm -rf *.test

docker:
    BUILD +docker-part-one
    BUILD +docker-part-two

docker-part-one:
    COPY +build/solution .
    COPY data ./data
    ENTRYPOINT ["/aoc/solution", "data/input.txt", "one"]
    LABEL org.opencontainers.image.source=https://github.com/lucasclerissepro/aoc
    SAVE IMAGE --push ghcr.io/lucasclerissepro/aoc-2022-5-one:latest

docker-part-two:
    COPY +build/solution .
    COPY data ./data
    ENTRYPOINT ["/aoc/solution", "data/input.txt", "two"]
    LABEL org.opencontainers.image.source=https://github.com/lucasclerissepro/aoc
    SAVE IMAGE --push ghcr.io/lucasclerissepro/aoc-2022-5-two:latest
